### ISSUE TITLE
query

### ISSUE THREAD

**Issue by bianchuanxin** [weifantt/DEPTS#1]
in utils.py, line: 122
why use add to check if they are equivalent?

**Comment by weifantt** [comment]
If you run FFT transformation for a signal, you will find out there are always adjacent pairs of 'symmetrical' signals (two signals whose frequencies and phases are opposite, say, frequency1+frequency2=0, phase1+phase2=0). Since cosine(x) = cosine(-x), we can regard these two cosine functions as one period by adding their amplitudes.

**Comment by bianchuanxin** [comment]
got it, thanks
